title: Prince Control Plane
description: Real networking labs, failures, and fixes
remote_theme: mmistakes/minimal-mistakes
markdown: kramdown

plugins:
  - jekyll-include-cache
defaults:
  - scope:
      path: ""
      type: posts
    values:
      classes: wide
      navigation:
  - title: "Home"
    url: /prince-site/
  - title: "Switching"
    url: /prince-site/issues/cisco/switches/
  - title: "Routing"
    url: /prince-site/issues/cisco/routing/
  - title: "Security"
    url: /prince-site/issues/security/

